### PR TITLE
Update project 🎉

### PR DESCRIPTION
**Pull request by asyl**
- Update Swift syntax version ~> 3.0
- Update Realm & RealmSwift version ~> 2.10.0
- Remove Carthage
- Add CocoaPods

### CODE REVIEW

**Comment by pietbrauer** [comment]
Hey, thanks a lot for the PullRequest. I am curious to know why you removed Carthage? There should be ways to support both CocoaPods and Carthage.

**Comment by asyl** [comment]
Ah, then, sorry :) I'm gonna add Carthage to the next pull request. Do I have to close this one?

**Comment by pietbrauer** [comment]
Ah sorry, I confused the project yesterday evening. Makes no sense to support both in a project of course, my fault.

I will have a look next week. Thanks for the pull request again!

**Comment by pietbrauer** [comment]
Thanks a lot!

**Pull request merged**
